// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIIyqlILtRJ8nKwU2vydYIGvTCAbNpGLM',
    appId: '1:111503786110:android:2b4e06bf18dad17d5dd82f',
    messagingSenderId: '111503786110',
    projectId: 'chatfaekon-806e9',
    storageBucket: 'chatfaekon-806e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hyBD-lwPsd4ewltsTqVdQbEKqDZC_pk',
    appId: '1:111503786110:ios:4f528cd3a6e5505b5dd82f',
    messagingSenderId: '111503786110',
    projectId: 'chatfaekon-806e9',
    storageBucket: 'chatfaekon-806e9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Vdl_ns_MoJQ5cXx8_E740C4X2PagRoY',
    appId: '1:111503786110:web:e54d18901e78db995dd82f',
    messagingSenderId: '111503786110',
    projectId: 'chatfaekon-806e9',
    authDomain: 'chatfaekon-806e9.firebaseapp.com',
    storageBucket: 'chatfaekon-806e9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_hyBD-lwPsd4ewltsTqVdQbEKqDZC_pk',
    appId: '1:111503786110:ios:4f528cd3a6e5505b5dd82f',
    messagingSenderId: '111503786110',
    projectId: 'chatfaekon-806e9',
    storageBucket: 'chatfaekon-806e9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Vdl_ns_MoJQ5cXx8_E740C4X2PagRoY',
    appId: '1:111503786110:web:fdafd34d36e7592a5dd82f',
    messagingSenderId: '111503786110',
    projectId: 'chatfaekon-806e9',
    authDomain: 'chatfaekon-806e9.firebaseapp.com',
    storageBucket: 'chatfaekon-806e9.firebasestorage.app',
  );

}